apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: sit-
namespace: sit

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: simple-deployment